server:
  port: 9001
spring:
  application:
    name: chengxuwang-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.235.235:3306/chengxuwang_base?characterEncoding=utf-8
    username: root
    password: "123456"
  jpa:
    database: MySql
    show-sql: true
    generate-ddl: true
eureka:
  client:
    serviceUrl:             #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true