server:
  port: 9010
spring:
  application:
    name: chengxuwang-friend

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.235.235:3306/chengxuwang_friend?characterEncoding=utf-8&&useSSL=false
    username: root
    password: "123456"
  rabbitmq:
    host: 192.168.235.235
  jpa:
    database: mysql
    show-sql: true
    open-in-view: false
jwt:
  config:
    key: chengxuwang
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true   #模块之间可以跨域访问
