server:
  port: 9007
spring:
  application:
    name: chengxuwang_search
  data:
    elasticsearch:
      cluster-nodes: 192.168.235.235:9300
  rabbitmq:
    host: 192.168.235.235
eureka:
  client:
    serviceUrl:             #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true
