server:
  port: 9006
spring:
  application:
    name: chengxuwang-spit
  data:
    mongodb:
      host: 192.168.235.235
      database: spitdb
  redis:
    host: 192.168.235.235
eureka:
  client:
    serviceUrl:             #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true