server: 
  port: 9008
spring: 
  application:  
    name: chengxuwang-user #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.235.235:3306/chengxuwang_user?characterEncoding=UTF8&&useSSL=false
    username: root
    password: "123456"
  jpa: 
    database: MySQL
    show-sql: true
    open-in-view: false
  redis:
    host: 192.168.235.235
  rabbitmq:
    host: 192.168.235.235
jwt:
  config:
    key: itcast
    ttl: 3600000
eureka:
  client:
    serviceUrl:             #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true