server:
  port: 9012
spring:
  application:
    name: chengxuwang-web
  rabbitmq:
    host: 192.168.235.235
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    chengxuwang-gathering:
      path: /gathering/**
      serviceId: chengxuwang-gathering
    chengxuwang-base:
      path: /base/**
      serviceId: chengxuwang-base
    chengxuwang-friend:
      path: /friend/**
      serviceId: chengxuwang-friend
    chengxuwang-qa:
      path: /qa/**
      serviceId: chengxuwang-qa
    chengxuwang-recruit:
      path: /recruit/**
      serviceId: chengxuwang-recruit
    chengxuwang-spit:
      path: /spit/**
      serviceId: chengxuwang-spit
    chengxuwang-user:
      path: /user/**
      serviceId: chengxuwang-user
    chengxuwang-search:
      path: /search/**
      serviceId: chengxuwang-search
    chengxuwang‐article:
      path: /article/**
      serviceId: chengxuwang-article
